version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartcity-app
    ports:
      - "8080:8080"
    environment:
#     SPRING_DATA_MONGODB_URI: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongo:27017/smartcity?authSource=admin
      SPRING_DATA_MONGODB_URI: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@fiap-simple-api-smartcity-c4cmf8exgca0bag5.brazilsouth-01.azurewebsites.net:27017/smartcity?authSource=admin&retryWrites=true&w=majority


      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mongo
    networks:
      - smartcity-network

volumes:
  mongo-data:
    driver: local

networks:
  smartcity-network:
    driver: bridge

