name: 01 - Actions - Validating

on:
  push:

jobs:
  checkout_java_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false

      - name: Executar scripts
        run: |
          git branch
          java --version 
          mvn clean package

      - name: Executar Testes
        run: mvn test

      - name: Validando adicoes
        run: mvn compile